---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  dnsmasq:
    build:
      context: '.'
    image: 'mireiawen/dnsmasq-config:latest'
    volumes:
    - type: 'bind'
      source: './files'
      target: '/app/files'
      read_only: true
    - type: 'tmpfs'
      target: '/app/templates_c'
    labels:
    - 'traefik.enable=false'
